#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VIFaculty")]
public partial class dataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertStd_Log(Std_Log instance);
  partial void UpdateStd_Log(Std_Log instance);
  partial void DeleteStd_Log(Std_Log instance);
  partial void InsertTeacher(Teacher instance);
  partial void UpdateTeacher(Teacher instance);
  partial void DeleteTeacher(Teacher instance);
  partial void InsertStudent(Student instance);
  partial void UpdateStudent(Student instance);
  partial void DeleteStudent(Student instance);
  partial void InsertLecture(Lecture instance);
  partial void UpdateLecture(Lecture instance);
  partial void DeleteLecture(Lecture instance);
  #endregion
	
	public dataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VIFacultyConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Std_Log> Std_Logs
	{
		get
		{
			return this.GetTable<Std_Log>();
		}
	}
	
	public System.Data.Linq.Table<Teacher> Teachers
	{
		get
		{
			return this.GetTable<Teacher>();
		}
	}
	
	public System.Data.Linq.Table<Student> Students
	{
		get
		{
			return this.GetTable<Student>();
		}
	}
	
	public System.Data.Linq.Table<Lecture> Lectures
	{
		get
		{
			return this.GetTable<Lecture>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Std_Log")]
public partial class Std_Log : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _log_id;
	
	private int _std_id;
	
	private string _std_log_name;
	
	private string _std_log_pass;
	
	private System.Nullable<bool> _log_active;
	
	private EntityRef<Student> _Student;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void Onstd_idChanging(int value);
    partial void Onstd_idChanged();
    partial void Onstd_log_nameChanging(string value);
    partial void Onstd_log_nameChanged();
    partial void Onstd_log_passChanging(string value);
    partial void Onstd_log_passChanged();
    partial void Onlog_activeChanging(System.Nullable<bool> value);
    partial void Onlog_activeChanged();
    #endregion
	
	public Std_Log()
	{
		this._Student = default(EntityRef<Student>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int log_id
	{
		get
		{
			return this._log_id;
		}
		set
		{
			if ((this._log_id != value))
			{
				this.Onlog_idChanging(value);
				this.SendPropertyChanging();
				this._log_id = value;
				this.SendPropertyChanged("log_id");
				this.Onlog_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_id", DbType="Int NOT NULL")]
	public int std_id
	{
		get
		{
			return this._std_id;
		}
		set
		{
			if ((this._std_id != value))
			{
				if (this._Student.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onstd_idChanging(value);
				this.SendPropertyChanging();
				this._std_id = value;
				this.SendPropertyChanged("std_id");
				this.Onstd_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_log_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string std_log_name
	{
		get
		{
			return this._std_log_name;
		}
		set
		{
			if ((this._std_log_name != value))
			{
				this.Onstd_log_nameChanging(value);
				this.SendPropertyChanging();
				this._std_log_name = value;
				this.SendPropertyChanged("std_log_name");
				this.Onstd_log_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_log_pass", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string std_log_pass
	{
		get
		{
			return this._std_log_pass;
		}
		set
		{
			if ((this._std_log_pass != value))
			{
				this.Onstd_log_passChanging(value);
				this.SendPropertyChanging();
				this._std_log_pass = value;
				this.SendPropertyChanged("std_log_pass");
				this.Onstd_log_passChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_active", DbType="Bit")]
	public System.Nullable<bool> log_active
	{
		get
		{
			return this._log_active;
		}
		set
		{
			if ((this._log_active != value))
			{
				this.Onlog_activeChanging(value);
				this.SendPropertyChanging();
				this._log_active = value;
				this.SendPropertyChanged("log_active");
				this.Onlog_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Std_Log", Storage="_Student", ThisKey="std_id", OtherKey="std_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public Student Student
	{
		get
		{
			return this._Student.Entity;
		}
		set
		{
			Student previousValue = this._Student.Entity;
			if (((previousValue != value) 
						|| (this._Student.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Student.Entity = null;
					previousValue.Std_Logs.Remove(this);
				}
				this._Student.Entity = value;
				if ((value != null))
				{
					value.Std_Logs.Add(this);
					this._std_id = value.std_id;
				}
				else
				{
					this._std_id = default(int);
				}
				this.SendPropertyChanged("Student");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teacher")]
public partial class Teacher : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _t_id;
	
	private string _t_fname;
	
	private string _t_lname;
	
	private string _t_father;
	
	private string _t_mother;
	
	private System.Nullable<System.DateTime> _t_birth_date;
	
	private string _t_birth_place;
	
	private System.Nullable<bool> _t_gender;
	
	private string _t_social_status;
	
	private string _t_diploma;
	
	private string _t_specialization;
	
	private string _t_email;
	
	private string _t_phone;
	
	private string _t_log_name;
	
	private string _t_log_pass;
	
	private string _t_picture;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ont_idChanging(int value);
    partial void Ont_idChanged();
    partial void Ont_fnameChanging(string value);
    partial void Ont_fnameChanged();
    partial void Ont_lnameChanging(string value);
    partial void Ont_lnameChanged();
    partial void Ont_fatherChanging(string value);
    partial void Ont_fatherChanged();
    partial void Ont_motherChanging(string value);
    partial void Ont_motherChanged();
    partial void Ont_birth_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ont_birth_dateChanged();
    partial void Ont_birth_placeChanging(string value);
    partial void Ont_birth_placeChanged();
    partial void Ont_genderChanging(System.Nullable<bool> value);
    partial void Ont_genderChanged();
    partial void Ont_social_statusChanging(string value);
    partial void Ont_social_statusChanged();
    partial void Ont_diplomaChanging(string value);
    partial void Ont_diplomaChanged();
    partial void Ont_specializationChanging(string value);
    partial void Ont_specializationChanged();
    partial void Ont_emailChanging(string value);
    partial void Ont_emailChanged();
    partial void Ont_phoneChanging(string value);
    partial void Ont_phoneChanged();
    partial void Ont_log_nameChanging(string value);
    partial void Ont_log_nameChanged();
    partial void Ont_log_passChanging(string value);
    partial void Ont_log_passChanged();
    partial void Ont_pictureChanging(string value);
    partial void Ont_pictureChanged();
    #endregion
	
	public Teacher()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int t_id
	{
		get
		{
			return this._t_id;
		}
		set
		{
			if ((this._t_id != value))
			{
				this.Ont_idChanging(value);
				this.SendPropertyChanging();
				this._t_id = value;
				this.SendPropertyChanged("t_id");
				this.Ont_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string t_fname
	{
		get
		{
			return this._t_fname;
		}
		set
		{
			if ((this._t_fname != value))
			{
				this.Ont_fnameChanging(value);
				this.SendPropertyChanging();
				this._t_fname = value;
				this.SendPropertyChanged("t_fname");
				this.Ont_fnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string t_lname
	{
		get
		{
			return this._t_lname;
		}
		set
		{
			if ((this._t_lname != value))
			{
				this.Ont_lnameChanging(value);
				this.SendPropertyChanging();
				this._t_lname = value;
				this.SendPropertyChanged("t_lname");
				this.Ont_lnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_father", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string t_father
	{
		get
		{
			return this._t_father;
		}
		set
		{
			if ((this._t_father != value))
			{
				this.Ont_fatherChanging(value);
				this.SendPropertyChanging();
				this._t_father = value;
				this.SendPropertyChanged("t_father");
				this.Ont_fatherChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_mother", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string t_mother
	{
		get
		{
			return this._t_mother;
		}
		set
		{
			if ((this._t_mother != value))
			{
				this.Ont_motherChanging(value);
				this.SendPropertyChanging();
				this._t_mother = value;
				this.SendPropertyChanged("t_mother");
				this.Ont_motherChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_birth_date", DbType="Date")]
	public System.Nullable<System.DateTime> t_birth_date
	{
		get
		{
			return this._t_birth_date;
		}
		set
		{
			if ((this._t_birth_date != value))
			{
				this.Ont_birth_dateChanging(value);
				this.SendPropertyChanging();
				this._t_birth_date = value;
				this.SendPropertyChanged("t_birth_date");
				this.Ont_birth_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_birth_place", DbType="VarChar(50)")]
	public string t_birth_place
	{
		get
		{
			return this._t_birth_place;
		}
		set
		{
			if ((this._t_birth_place != value))
			{
				this.Ont_birth_placeChanging(value);
				this.SendPropertyChanging();
				this._t_birth_place = value;
				this.SendPropertyChanged("t_birth_place");
				this.Ont_birth_placeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_gender", DbType="Bit")]
	public System.Nullable<bool> t_gender
	{
		get
		{
			return this._t_gender;
		}
		set
		{
			if ((this._t_gender != value))
			{
				this.Ont_genderChanging(value);
				this.SendPropertyChanging();
				this._t_gender = value;
				this.SendPropertyChanged("t_gender");
				this.Ont_genderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_social_status", DbType="VarChar(50)")]
	public string t_social_status
	{
		get
		{
			return this._t_social_status;
		}
		set
		{
			if ((this._t_social_status != value))
			{
				this.Ont_social_statusChanging(value);
				this.SendPropertyChanging();
				this._t_social_status = value;
				this.SendPropertyChanged("t_social_status");
				this.Ont_social_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_diploma", DbType="VarChar(50)")]
	public string t_diploma
	{
		get
		{
			return this._t_diploma;
		}
		set
		{
			if ((this._t_diploma != value))
			{
				this.Ont_diplomaChanging(value);
				this.SendPropertyChanging();
				this._t_diploma = value;
				this.SendPropertyChanged("t_diploma");
				this.Ont_diplomaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_specialization", DbType="VarChar(50)")]
	public string t_specialization
	{
		get
		{
			return this._t_specialization;
		}
		set
		{
			if ((this._t_specialization != value))
			{
				this.Ont_specializationChanging(value);
				this.SendPropertyChanging();
				this._t_specialization = value;
				this.SendPropertyChanged("t_specialization");
				this.Ont_specializationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string t_email
	{
		get
		{
			return this._t_email;
		}
		set
		{
			if ((this._t_email != value))
			{
				this.Ont_emailChanging(value);
				this.SendPropertyChanging();
				this._t_email = value;
				this.SendPropertyChanged("t_email");
				this.Ont_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_phone", DbType="VarChar(50)")]
	public string t_phone
	{
		get
		{
			return this._t_phone;
		}
		set
		{
			if ((this._t_phone != value))
			{
				this.Ont_phoneChanging(value);
				this.SendPropertyChanging();
				this._t_phone = value;
				this.SendPropertyChanged("t_phone");
				this.Ont_phoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_log_name", DbType="VarChar(50)")]
	public string t_log_name
	{
		get
		{
			return this._t_log_name;
		}
		set
		{
			if ((this._t_log_name != value))
			{
				this.Ont_log_nameChanging(value);
				this.SendPropertyChanging();
				this._t_log_name = value;
				this.SendPropertyChanged("t_log_name");
				this.Ont_log_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_log_pass", DbType="VarChar(50)")]
	public string t_log_pass
	{
		get
		{
			return this._t_log_pass;
		}
		set
		{
			if ((this._t_log_pass != value))
			{
				this.Ont_log_passChanging(value);
				this.SendPropertyChanging();
				this._t_log_pass = value;
				this.SendPropertyChanged("t_log_pass");
				this.Ont_log_passChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_picture", DbType="VarChar(150)")]
	public string t_picture
	{
		get
		{
			return this._t_picture;
		}
		set
		{
			if ((this._t_picture != value))
			{
				this.Ont_pictureChanging(value);
				this.SendPropertyChanging();
				this._t_picture = value;
				this.SendPropertyChanged("t_picture");
				this.Ont_pictureChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _std_id;
	
	private System.Nullable<int> _std_d_id;
	
	private string _std_fname;
	
	private string _std_lname;
	
	private string _std_father;
	
	private string _std_mother;
	
	private System.DateTime _std_birth_date;
	
	private string _std_birth_place;
	
	private bool _std_gender;
	
	private string _std_social_status;
	
	private string _std_diploma;
	
	private string _std_specialization;
	
	private string _std_email;
	
	private string _std_phone;
	
	private string _std_country;
	
	private string _std_city;
	
	private string _std_address;
	
	private System.Nullable<System.DateTime> _std_reg_date;
	
	private System.Nullable<int> _std_year;
	
	private System.Nullable<int> _std_remains_sub;
	
	private string _std_picture;
	
	private EntitySet<Std_Log> _Std_Logs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstd_idChanging(int value);
    partial void Onstd_idChanged();
    partial void Onstd_d_idChanging(System.Nullable<int> value);
    partial void Onstd_d_idChanged();
    partial void Onstd_fnameChanging(string value);
    partial void Onstd_fnameChanged();
    partial void Onstd_lnameChanging(string value);
    partial void Onstd_lnameChanged();
    partial void Onstd_fatherChanging(string value);
    partial void Onstd_fatherChanged();
    partial void Onstd_motherChanging(string value);
    partial void Onstd_motherChanged();
    partial void Onstd_birth_dateChanging(System.DateTime value);
    partial void Onstd_birth_dateChanged();
    partial void Onstd_birth_placeChanging(string value);
    partial void Onstd_birth_placeChanged();
    partial void Onstd_genderChanging(bool value);
    partial void Onstd_genderChanged();
    partial void Onstd_social_statusChanging(string value);
    partial void Onstd_social_statusChanged();
    partial void Onstd_diplomaChanging(string value);
    partial void Onstd_diplomaChanged();
    partial void Onstd_specializationChanging(string value);
    partial void Onstd_specializationChanged();
    partial void Onstd_emailChanging(string value);
    partial void Onstd_emailChanged();
    partial void Onstd_phoneChanging(string value);
    partial void Onstd_phoneChanged();
    partial void Onstd_countryChanging(string value);
    partial void Onstd_countryChanged();
    partial void Onstd_cityChanging(string value);
    partial void Onstd_cityChanged();
    partial void Onstd_addressChanging(string value);
    partial void Onstd_addressChanged();
    partial void Onstd_reg_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onstd_reg_dateChanged();
    partial void Onstd_yearChanging(System.Nullable<int> value);
    partial void Onstd_yearChanged();
    partial void Onstd_remains_subChanging(System.Nullable<int> value);
    partial void Onstd_remains_subChanged();
    partial void Onstd_pictureChanging(string value);
    partial void Onstd_pictureChanged();
    #endregion
	
	public Student()
	{
		this._Std_Logs = new EntitySet<Std_Log>(new Action<Std_Log>(this.attach_Std_Logs), new Action<Std_Log>(this.detach_Std_Logs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int std_id
	{
		get
		{
			return this._std_id;
		}
		set
		{
			if ((this._std_id != value))
			{
				this.Onstd_idChanging(value);
				this.SendPropertyChanging();
				this._std_id = value;
				this.SendPropertyChanged("std_id");
				this.Onstd_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_d_id", DbType="Int")]
	public System.Nullable<int> std_d_id
	{
		get
		{
			return this._std_d_id;
		}
		set
		{
			if ((this._std_d_id != value))
			{
				this.Onstd_d_idChanging(value);
				this.SendPropertyChanging();
				this._std_d_id = value;
				this.SendPropertyChanged("std_d_id");
				this.Onstd_d_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string std_fname
	{
		get
		{
			return this._std_fname;
		}
		set
		{
			if ((this._std_fname != value))
			{
				this.Onstd_fnameChanging(value);
				this.SendPropertyChanging();
				this._std_fname = value;
				this.SendPropertyChanged("std_fname");
				this.Onstd_fnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string std_lname
	{
		get
		{
			return this._std_lname;
		}
		set
		{
			if ((this._std_lname != value))
			{
				this.Onstd_lnameChanging(value);
				this.SendPropertyChanging();
				this._std_lname = value;
				this.SendPropertyChanged("std_lname");
				this.Onstd_lnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_father", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string std_father
	{
		get
		{
			return this._std_father;
		}
		set
		{
			if ((this._std_father != value))
			{
				this.Onstd_fatherChanging(value);
				this.SendPropertyChanging();
				this._std_father = value;
				this.SendPropertyChanged("std_father");
				this.Onstd_fatherChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_mother", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string std_mother
	{
		get
		{
			return this._std_mother;
		}
		set
		{
			if ((this._std_mother != value))
			{
				this.Onstd_motherChanging(value);
				this.SendPropertyChanging();
				this._std_mother = value;
				this.SendPropertyChanged("std_mother");
				this.Onstd_motherChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_birth_date", DbType="Date NOT NULL")]
	public System.DateTime std_birth_date
	{
		get
		{
			return this._std_birth_date;
		}
		set
		{
			if ((this._std_birth_date != value))
			{
				this.Onstd_birth_dateChanging(value);
				this.SendPropertyChanging();
				this._std_birth_date = value;
				this.SendPropertyChanged("std_birth_date");
				this.Onstd_birth_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_birth_place", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string std_birth_place
	{
		get
		{
			return this._std_birth_place;
		}
		set
		{
			if ((this._std_birth_place != value))
			{
				this.Onstd_birth_placeChanging(value);
				this.SendPropertyChanging();
				this._std_birth_place = value;
				this.SendPropertyChanged("std_birth_place");
				this.Onstd_birth_placeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_gender", DbType="Bit NOT NULL")]
	public bool std_gender
	{
		get
		{
			return this._std_gender;
		}
		set
		{
			if ((this._std_gender != value))
			{
				this.Onstd_genderChanging(value);
				this.SendPropertyChanging();
				this._std_gender = value;
				this.SendPropertyChanged("std_gender");
				this.Onstd_genderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_social_status", DbType="VarChar(50)")]
	public string std_social_status
	{
		get
		{
			return this._std_social_status;
		}
		set
		{
			if ((this._std_social_status != value))
			{
				this.Onstd_social_statusChanging(value);
				this.SendPropertyChanging();
				this._std_social_status = value;
				this.SendPropertyChanged("std_social_status");
				this.Onstd_social_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_diploma", DbType="VarChar(50)")]
	public string std_diploma
	{
		get
		{
			return this._std_diploma;
		}
		set
		{
			if ((this._std_diploma != value))
			{
				this.Onstd_diplomaChanging(value);
				this.SendPropertyChanging();
				this._std_diploma = value;
				this.SendPropertyChanged("std_diploma");
				this.Onstd_diplomaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_specialization", DbType="VarChar(50)")]
	public string std_specialization
	{
		get
		{
			return this._std_specialization;
		}
		set
		{
			if ((this._std_specialization != value))
			{
				this.Onstd_specializationChanging(value);
				this.SendPropertyChanging();
				this._std_specialization = value;
				this.SendPropertyChanged("std_specialization");
				this.Onstd_specializationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string std_email
	{
		get
		{
			return this._std_email;
		}
		set
		{
			if ((this._std_email != value))
			{
				this.Onstd_emailChanging(value);
				this.SendPropertyChanging();
				this._std_email = value;
				this.SendPropertyChanged("std_email");
				this.Onstd_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_phone", DbType="VarChar(50)")]
	public string std_phone
	{
		get
		{
			return this._std_phone;
		}
		set
		{
			if ((this._std_phone != value))
			{
				this.Onstd_phoneChanging(value);
				this.SendPropertyChanging();
				this._std_phone = value;
				this.SendPropertyChanged("std_phone");
				this.Onstd_phoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_country", DbType="VarChar(50)")]
	public string std_country
	{
		get
		{
			return this._std_country;
		}
		set
		{
			if ((this._std_country != value))
			{
				this.Onstd_countryChanging(value);
				this.SendPropertyChanging();
				this._std_country = value;
				this.SendPropertyChanged("std_country");
				this.Onstd_countryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_city", DbType="VarChar(50)")]
	public string std_city
	{
		get
		{
			return this._std_city;
		}
		set
		{
			if ((this._std_city != value))
			{
				this.Onstd_cityChanging(value);
				this.SendPropertyChanging();
				this._std_city = value;
				this.SendPropertyChanged("std_city");
				this.Onstd_cityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_address", DbType="VarChar(50)")]
	public string std_address
	{
		get
		{
			return this._std_address;
		}
		set
		{
			if ((this._std_address != value))
			{
				this.Onstd_addressChanging(value);
				this.SendPropertyChanging();
				this._std_address = value;
				this.SendPropertyChanged("std_address");
				this.Onstd_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_reg_date", DbType="Date")]
	public System.Nullable<System.DateTime> std_reg_date
	{
		get
		{
			return this._std_reg_date;
		}
		set
		{
			if ((this._std_reg_date != value))
			{
				this.Onstd_reg_dateChanging(value);
				this.SendPropertyChanging();
				this._std_reg_date = value;
				this.SendPropertyChanged("std_reg_date");
				this.Onstd_reg_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_year", DbType="Int")]
	public System.Nullable<int> std_year
	{
		get
		{
			return this._std_year;
		}
		set
		{
			if ((this._std_year != value))
			{
				this.Onstd_yearChanging(value);
				this.SendPropertyChanging();
				this._std_year = value;
				this.SendPropertyChanged("std_year");
				this.Onstd_yearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_remains_sub", DbType="Int")]
	public System.Nullable<int> std_remains_sub
	{
		get
		{
			return this._std_remains_sub;
		}
		set
		{
			if ((this._std_remains_sub != value))
			{
				this.Onstd_remains_subChanging(value);
				this.SendPropertyChanging();
				this._std_remains_sub = value;
				this.SendPropertyChanged("std_remains_sub");
				this.Onstd_remains_subChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_std_picture", DbType="VarChar(150)")]
	public string std_picture
	{
		get
		{
			return this._std_picture;
		}
		set
		{
			if ((this._std_picture != value))
			{
				this.Onstd_pictureChanging(value);
				this.SendPropertyChanging();
				this._std_picture = value;
				this.SendPropertyChanged("std_picture");
				this.Onstd_pictureChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Std_Log", Storage="_Std_Logs", ThisKey="std_id", OtherKey="std_id")]
	public EntitySet<Std_Log> Std_Logs
	{
		get
		{
			return this._Std_Logs;
		}
		set
		{
			this._Std_Logs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Std_Logs(Std_Log entity)
	{
		this.SendPropertyChanging();
		entity.Student = this;
	}
	
	private void detach_Std_Logs(Std_Log entity)
	{
		this.SendPropertyChanging();
		entity.Student = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lecture")]
public partial class Lecture : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _l_id;
	
	private int _c_id;
	
	private int _l_num;
	
	private string _l_name;
	
	private System.Nullable<System.DateTime> _l_date;
	
	private System.Nullable<System.TimeSpan> _l_time;
	
	private string _l_file;
	
	private string _l_pdf;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onl_idChanging(int value);
    partial void Onl_idChanged();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void Onl_numChanging(int value);
    partial void Onl_numChanged();
    partial void Onl_nameChanging(string value);
    partial void Onl_nameChanged();
    partial void Onl_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onl_dateChanged();
    partial void Onl_timeChanging(System.Nullable<System.TimeSpan> value);
    partial void Onl_timeChanged();
    partial void Onl_fileChanging(string value);
    partial void Onl_fileChanged();
    partial void Onl_pdfChanging(string value);
    partial void Onl_pdfChanged();
    #endregion
	
	public Lecture()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int l_id
	{
		get
		{
			return this._l_id;
		}
		set
		{
			if ((this._l_id != value))
			{
				this.Onl_idChanging(value);
				this.SendPropertyChanging();
				this._l_id = value;
				this.SendPropertyChanged("l_id");
				this.Onl_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int NOT NULL")]
	public int c_id
	{
		get
		{
			return this._c_id;
		}
		set
		{
			if ((this._c_id != value))
			{
				this.Onc_idChanging(value);
				this.SendPropertyChanging();
				this._c_id = value;
				this.SendPropertyChanged("c_id");
				this.Onc_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_num", DbType="Int NOT NULL")]
	public int l_num
	{
		get
		{
			return this._l_num;
		}
		set
		{
			if ((this._l_num != value))
			{
				this.Onl_numChanging(value);
				this.SendPropertyChanging();
				this._l_num = value;
				this.SendPropertyChanged("l_num");
				this.Onl_numChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_name", DbType="VarChar(50)")]
	public string l_name
	{
		get
		{
			return this._l_name;
		}
		set
		{
			if ((this._l_name != value))
			{
				this.Onl_nameChanging(value);
				this.SendPropertyChanging();
				this._l_name = value;
				this.SendPropertyChanged("l_name");
				this.Onl_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_date", DbType="Date")]
	public System.Nullable<System.DateTime> l_date
	{
		get
		{
			return this._l_date;
		}
		set
		{
			if ((this._l_date != value))
			{
				this.Onl_dateChanging(value);
				this.SendPropertyChanging();
				this._l_date = value;
				this.SendPropertyChanged("l_date");
				this.Onl_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_time", DbType="Time")]
	public System.Nullable<System.TimeSpan> l_time
	{
		get
		{
			return this._l_time;
		}
		set
		{
			if ((this._l_time != value))
			{
				this.Onl_timeChanging(value);
				this.SendPropertyChanging();
				this._l_time = value;
				this.SendPropertyChanged("l_time");
				this.Onl_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_file", DbType="VarChar(50)")]
	public string l_file
	{
		get
		{
			return this._l_file;
		}
		set
		{
			if ((this._l_file != value))
			{
				this.Onl_fileChanging(value);
				this.SendPropertyChanging();
				this._l_file = value;
				this.SendPropertyChanged("l_file");
				this.Onl_fileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_pdf", DbType="VarChar(50)")]
	public string l_pdf
	{
		get
		{
			return this._l_pdf;
		}
		set
		{
			if ((this._l_pdf != value))
			{
				this.Onl_pdfChanging(value);
				this.SendPropertyChanging();
				this._l_pdf = value;
				this.SendPropertyChanged("l_pdf");
				this.Onl_pdfChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
